### PR TITLE
reddit: add support for user post links & clean up

### LINKED ISSUE #474: Add support for user posts on Reddit
gif is broken srry

✅ https://www.reddit.com/r/test_axolotl/comments/1cg2hhf/test/
❌ https://www.reddit.com/user/gxaura_/comments/1cg2gar/test/

### PR DESCRIPTION
**Pull request by wukko**
closes #474

### CODE REVIEW

File: src/modules/processing/services/reddit.js [hunk 1]
```diff
@@ -48,43 +48,78 @@ async function getAccessToken() {
...
     const accessToken = await getAccessToken();
     if (accessToken) url.hostname = 'oauth.reddit.com';
 
     let data = await fetch(
-        url, { headers: accessToken && { authorization: `Bearer ${accessToken}` } }
-    ).then((r) => { return r.json() }).catch(() => { return false });
-    if (!data) return { error: 'ErrorCouldntFetch' };
+        url, {
+            headers: {
+                authorization: `Bearer ${accessToken}`,
```
Comment (dumbmoron) [inline src/modules/processing/services/reddit.js:63]: the `accessToken && ...` is needed, ``` `Bearer ${accessToken}` ``` sends `'Bearer undefined'` if there is no accessToken

File: src/modules/processing/services/reddit.js [hunk 2]
```diff
@@ -48,43 +48,78 @@ async function getAccessToken() {
...
     // fallback for videos with variable audio quality
     if (!audio) {
         audioFileLink = `${video.split('_')[0]}_AUDIO_128.mp4`
-        await fetch(audioFileLink, { method: "HEAD" }).then((r) => { if (Number(r.status) === 200) audio = true }).catch(() => { audio = false });
+        await fetch(audioFileLink, { method: "HEAD" }).then((r) => {
+            if (Number(r.status) === 200) {
+                audio = true
+            }
+        }).catch(() => {
+            audio = false
```
Comment (dumbmoron) [inline src/modules/processing/services/reddit.js:107]: i don't think this assignment changes anything?

**Review by dumbmoron — CHANGES_REQUESTED** [review]

File: src/modules/processing/services/reddit.js (hunk 1 above)
Comment (dumbmoron) [reply src/modules/processing/services/reddit.js:63]: (and it breaks reddit downloads for instances with no cookies)

**Review by dumbmoron — APPROVED** [review]
image
