### PR TITLE
tumblr: use mobile api & fix audio support

### LINKED ISSUE #342: Add support for Tumblr audio
I've noticed that attempting to get audio posted in a Tumblr post does not work with cobalt, and would like to have this feature implemented.

For example: https://www.tumblr.com/zedneon/737815079301562368/zedneon-ft-mr-sauceman-tech-n9ne-speed-of?source=share
This post has one audio file attached. For posts with multiple audio(and/or video) files attached, it may be good to make a list of all of the files appear, and you cn simply click the one(s) you'd like to download.

### PR DESCRIPTION
**Pull request by dumbmoron**
closes #342

### CODE REVIEW

**Review by wukko — APPROVED** [review]

File: src/modules/processing/services/tumblr.js [hunk 1]
```diff
@@ -1,35 +1,71 @@
 import psl from "psl";
 import { genericUserAgent } from "../../config.js";
 
-export default async function(obj) {
-    let { subdomain } = psl.parse(obj.url.hostname);
+const API_KEY = 'jrsCWX1XDuVxAFO4GkK147syAoN8BJZ5voz8tS80bPcj26Vc5Z';
```
Comment (wukko) [inline src/modules/processing/services/tumblr.js:4]: where is this api key from?

Comment (dumbmoron) [reply src/modules/processing/services/tumblr.js:4]: yes
